# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Template.create(:description => "Famosos")
Template.create(:description => "Personajes")
Template.create(:description => "Amigos")

Card.create(:description => "Antonio Banderas", :url => "img/cartas/f_banderas.jpg", :template_id => 1)
Card.create(:description => "Beyonce", :url => "img/cartas/f_beyonce.jpg", :template_id => 1)
Card.create(:description => "Angelique Boyer", :url => "img/cartas/f_boyer.jpg", :template_id => 1)
Card.create(:description => "Daniel Craig", :url => "img/cartas/f_craig.jpg", :template_id => 1)
Card.create(:description => "Robert De Niro", :url => "img/cartas/f_deniro.jpg", :template_id => 1)
Card.create(:description => "Leonardo DiCaprio", :url => "img/cartas/f_dicaprio.jpg", :template_id => 1)
Card.create(:description => "Robert Downey Jr", :url => "img/cartas/f_downey.jpg", :template_id => 1)
Card.create(:description => "Carmen Electra", :url => "img/cartas/f_electra.jpg", :template_id => 1)
Card.create(:description => "Megan Fox", :url => "img/cartas/f_fox.jpg", :template_id => 1)
Card.create(:description => "Selena Gomez", :url => "img/cartas/f_gomez.jpg", :template_id => 1)
Card.create(:description => "Tom Hanks", :url => "img/cartas/f_hanks.jpg", :template_id => 1)
Card.create(:description => "Salma Hayek", :url => "img/cartas/f_hayek.jpg", :template_id => 1)
Card.create(:description => "Hugh Jackman", :url => "img/cartas/f_jackman.jpg", :template_id => 1)
Card.create(:description => "Scarlet Johannson", :url => "img/cartas/f_johansson.jpg", :template_id => 1)
Card.create(:description => "Nicole Kidman", :url => "img/cartas/f_kidman.jpg", :template_id => 1)
Card.create(:description => "Demi Lovato", :url => "img/cartas/f_lovato.jpg", :template_id => 1)
Card.create(:description => "Tobey Maguire", :url => "img/cartas/f_maguire.jpg", :template_id => 1)
Card.create(:description => "Rafa Marquez", :url => "img/cartas/f_marquez.jpg", :template_id => 1)
Card.create(:description => "Natalie Portman", :url => "img/cartas/f_portman.jpg", :template_id => 1)
Card.create(:description => "Daniel Radcliffe", :url => "img/cartas/f_radcliffe.jpg", :template_id => 1)
Card.create(:description => "Cristiano Ronaldo", :url => "img/cartas/f_ronaldo.jpg", :template_id => 1)
Card.create(:description => "Pablo Montero", :url => "img/cartas/f_montero.jpg", :template_id => 1)
Card.create(:description => "Gabriel Soto", :url => "img/cartas/f_soto.jpg", :template_id => 1)
Card.create(:description => "Thalia", :url => "img/cartas/f_thalia.jpg", :template_id => 1)
Card.create(:description => "Emma Watson", :url => "img/cartas/f_watson.jpg", :template_id => 1)
Card.create(:description => "Adan", :url => "img/cartas/p_adan.jpg", :template_id => 2)
Card.create(:description => "Alberto", :url => "img/cartas/p_alberto.jpg", :template_id => 2)
Card.create(:description => "Alejandro", :url => "img/cartas/p_alejandro.jpg", :template_id => 2)
Card.create(:description => "Andres", :url => "img/cartas/p_andres.jpg", :template_id => 2)
Card.create(:description => "Armando", :url => "img/cartas/p_armando.jpg", :template_id => 2)
Card.create(:description => "Arturo", :url => "img/cartas/p_arturo.jpg", :template_id => 2)
Card.create(:description => "Cesar", :url => "img/cartas/p_cesar.jpg", :template_id => 2)
Card.create(:description => "Concha", :url => "img/cartas/p_concha.jpg", :template_id => 2)
Card.create(:description => "David", :url => "img/cartas/p_david.jpg", :template_id => 2)
Card.create(:description => "Ernesto", :url => "img/cartas/p_ernesto.jpg", :template_id => 2)
Card.create(:description => "Gaby", :url => "img/cartas/p_gaby.jpg", :template_id => 2)
Card.create(:description => "Hector", :url => "img/cartas/p_hector.jpg", :template_id => 2)
Card.create(:description => "Humberto", :url => "img/cartas/p_humberto.jpg", :template_id => 2)
Card.create(:description => "Ivan", :url => "img/cartas/p_ivan.jpg", :template_id => 2)
Card.create(:description => "Jaime", :url => "img/cartas/p_jaime.jpg", :template_id => 2)
Card.create(:description => "Jake", :url => "img/cartas/p_jake.jpg", :template_id => 2)
Card.create(:description => "Jose", :url => "img/cartas/p_jose.jpg", :template_id => 2)
Card.create(:description => "Julio", :url => "img/cartas/p_julio.jpg", :template_id => 2)
Card.create(:description => "Lilian", :url => "img/cartas/p_lilian.jpg", :template_id => 2)
Card.create(:description => "Marcela", :url => "img/cartas/p_marcela.jpg", :template_id => 2)
Card.create(:description => "Mariana", :url => "img/cartas/p_mariana.jpg", :template_id => 2)
Card.create(:description => "Mario", :url => "img/cartas/p_mario.jpg", :template_id => 2)
Card.create(:description => "Paco", :url => "img/cartas/p_paco.jpg", :template_id => 2)
Card.create(:description => "Pilar", :url => "img/cartas/p_pilar.jpg", :template_id => 2)
Card.create(:description => "Raquel", :url => "img/cartas/p_raquel.jpg", :template_id => 2)
Card.create(:description => "Roberto", :url => "img/cartas/p_roberto.jpg", :template_id => 2)
Card.create(:description => "Rodrigo", :url => "img/cartas/p_rodrigo.jpg", :template_id => 2)
Card.create(:description => "Salvador", :url => "img/cartas/p_salvador.jpg", :template_id => 2)
Card.create(:description => "Sarah", :url => "img/cartas/p_sarah.jpg", :template_id => 2)
Card.create(:description => "Sergio", :url => "img/cartas/p_sergio.jpg", :template_id => 2)
Card.create(:description => "Ximena", :url => "img/cartas/p_ximena.jpg", :template_id => 2)